title: ZhangHe
repo: hertzZhang/hertzZhang.github.io
email: zhanghelook@outlook.com
description: "生活并无完美，与其让生活带来更多的沮丧与抱怨，不如坚持着一份信念，相信通过努力可以让生活变得更好。"
excerpt_separator: "true"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://zhanghe.org"
lang: zh
paginate: 10
paginate_path: "/page/:num"
metaAuthor: "张赫"
blogName: "张赫的博客"
appTitle: "张赫的博客"
twitter_username: hertzZhang
github_username: hertzZhang
destination: "./gphome"
collections:
  authors:
    output: true
  staff_members:
    output: true
    # people: true

author:
  twitter: hertzZhang

baidu:
  appid: 1612867930592980

ga:
  userid: UA-125234893-1

twitter:
  username: hertzZhang
  card: summary_large_image
  site: "@hertzZhang"

defaults:
  - scope:
      path: "_authors"
      type: "posts"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "zhanghe"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-remote-theme

markdown: kramdown
remote_theme: hertzZhang/yoyoyo
