# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: zhanghe
repo: hertzZhang/hertzZhang.github.io
email: zhangheorg@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  生活并无完美，与其让生活带来更多的沮丧与抱怨，不如坚持着一份信念，相信通过努力可以让生活变得更好。
excerpt_separator: true
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://zhanghe.org" # the base hostname & protocol for your site, e.g. http://example.com
lang: zh
paginate: 10
paginate_path: "/page/:num"
twitter_username: hertzZhang
github_username:  hertzZhang
collections:
  authors:
    output: true
  staff_members:
    output: true
    # people: true

author:
  twitter: hertzZhang

baidu:
  appid: 1612867930592980

ga:
  userid: UA-125234893-1

twitter:
  username: hertzZhang
  card: summary_large_image
  site: '@hertzZhang'

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Build settings
markdown: kramdown
theme: minima
remote_theme: yoyoyo
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
